ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure("2") do |config|
   config.ssh.port = "22"
   config.ssh.forward_agent = true
   config.vm.define "ds2" do |a|
      a.vm.provider "docker" do |d|
         d.build_dir = "."
         d.build_args = ["-t=ds2"]
         d.name = "ds2"
         d.has_ssh =true
         d.remains_running = true
         d.ports = [ "2389:2389" ]
      end
   end
end

